run:
    timeout: 5m

linters-settings:
    gci:
        sections:
            - standard
            - default
            - prefix(github.com/go-viper/mapstructure)
    goimports:
        local-prefixes: github.com/go-viper/maptstructure

linters:
    disable-all: true
    enable:
        - gci
        - gofmt
        - gofumpt
        - goimports
        - staticcheck
        # - stylecheck
